trigger:
- master

variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '0'
  Patch: '1'

jobs:
- job: 'Ubuntu'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: dotnet build
    displayName: 'Dotnet build $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: 'Dotnet test $(buildConfiguration)'
    inputs:
      command: test
      projects: '**/*Tests/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

- job: 'Windows'
  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  - script: dotnet build
    displayName: 'Dotnet build $(buildConfiguration)'

  - task: NuGetCommand@2
    displayName: 'Dotnet pack'
    inputs:
      command: pack
      packagesToPack: '**/*.csproj'
      versioningScheme: byPrereleaseNumber
      majorVersion: '$(Major)'
      minorVersion: '$(Minor)'
      patchVersion: '$(Patch)'
